# Generated by Django 3.1.2 on 2020-10-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
